#!/bin/sh

LN="ln"
RCFILES=".bashrc .inputrc .vimrc .cdargs .gitconfig .cdargsresult .bash_logout .gitk .bash_profile"

for rcfile in $RCFILES; do 
	if [ -f $HOME/$rcfile ]; then
		echo "$HOME/$rcfile exists, exit.";
		exit;
	fi
done


for rcfile in $RCFILES; do 
	if [ -f $HOME/$rcfile ]; then
		$LN -sf $rcfile $HOME/$rcfile
	fi
done

